FROM --platform=linux/amd64 ubuntu:20.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential python3 python3-pip pkg-config libdbus-1-dev libasound-dev libudev-dev git ninja-build libsndfile-dev
RUN pip3 install meson

ADD . /repo
WORKDIR /repo
RUN meson setup builddir -Dpw-cat=enabled
RUN ninja -C builddir
